sonar.projectKey=karelinaas_python-project-50
sonar.organization=karelinaas

# Path to sources
sonar.sources=gendiff

# Path to tests
sonar.tests=tests

# Coverage reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/__pycache__/**,**/tests/**

# Python version
sonar.python.version=3.12

# Encoding
sonar.sourceEncoding=UTF-8
